srcs = ['src/compile_db.cppm', 'src/main.cpp']
compile_args = ["-std=c++26"]
link_args = []

[dependencies]
boost = {modules = ["system", "program_options", "process"]}
tomlplusplus = {}
nlohmann_json = {}
