srcs = ['src/config.cppm', 'src/compile_db.cppm', 'src/main.cpp']
compile_args = ["-std=c++26", "-DTOMLPLUSPLUS_BUILD_MODULES"]
link_args = ["-lc"]

[dependencies]
boost = {modules = ["system", "program_options", "process"]}
tomlplusplus = {}
nlohmann_json = {}
