on: [push]
jobs:
  build:
    runs-on: kaylee
    steps:
      - uses: actions/checkout@v4

      - uses: https://github.com/DeterminateSystems/nix-installer-action@v20
        with:
          flakehub: false
   
      - name: Build
        run: |
          nix build -L --no-pure-eval --accept-flake-config
          cd buildr
          nix develop --no-pure-eval --accept-flake-config --command bash -c "just build_f"
