on: [push]
jobs:
  build:
    runs-on: docker
    steps:
      - name: install nix
        run: |
          curl -sSf -L https://install.lix.systems/lix | sh -s -- install linux --no-confirm --init none

      - uses: actions/checkout@v4
    
      - name: Build
        run: |
          nix build
