srcs = ["src/logging.cppm", "src/toml.cpp", "src/config_mod.cppm", "src/dependencies_mod.cppm", "src/build_mod.cppm", "src/main.cpp"]
compile_args = ["-Isrc", "-std=c++26"]
link_args = []

[dependencies]
boost = {modules = ["program_options", "process", "json"]}
tomlplusplus = {}
nlohmann_json = {}
libpkgconf = {}
